#!/bin/bash
set -e

if git diff --cached --quiet; then
  echo "No staged changes found."
  exit 1
fi

echo "Checking for package.json and package-lock.json discrepancies..."
newPackageVersion=$(jq -r ".version" package.json)
newLockVersion=$(jq -r ".version" package-lock.json)
if [[ "$newPackageVersion" != "$newLockVersion" ]]; then
  echo "❌ ERROR: package.json and package-lock.json out of sync. Please run \`npm install\` to fix this."
  exit 1
else
  echo "package.json and package-lock.json versions in sync."
fi

npm run format
npm run lint
npm test

# Warn in the console if there are source code changes but version number has not been changed
if !(git diff --cached --quiet "src/*"); then
  oldPackageVersion=$(git show origin/main:package.json | jq -r ".version")
  if [[ "$oldPackageVersion" == "$newPackageVersion" ]]; then
      echo "⚠️ WARNING: Source code changes found but version has not been updated. Please run one of the following:"
      echo "- \`npm run change-major\` (e.g. v1.2.3 -> v2.0.0)"
      echo "- \`npm run change-minor\` (e.g. v1.2.3 -> v1.3.0)"
      echo "- \`npm run change-patch\` (e.g. v1.2.3 -> v1.2.4)"
  fi
fi

git update-index --again
